# This is a basic workflow to help you get started with Actions

name: AuditSecurity

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab and VS Code
  workflow_dispatch:

  # Allows you to run this workflow manually from VS Code
  repository_dispatch:
    types: [ auditsecurity ]

  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    - name: Perform Scan
      uses: ShiftLeftSecurity/scan-action@master
      with:
        type: "credscan,python"
      env:
        WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - uses: actions/upload-artifact@v1
      with:
        name: reports
        path: reports