# This is a basic workflow to help you get started with Actions

name: AZCreatePlaybooks

# Controls when the action will run.
# Allows you to run this workflow manually from the Actions tab and VS Code
on:
  # Allows you to run this workflow manually from the Actions tab and VS Code
  workflow_dispatch:

  # Allows you to run this workflow manually from VS Code
  repository_dispatch:
    types: [ azcreateplaybooks ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "validate-and-deploy"
  validate-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ARM Template
        run: |
          az deployment group create -g accorinvest --template-file Playbooks/Get-IPReputation/Get-IPReputation.json --parameters Playbooks/Playbooks.params Azure_ServiceAccount=${{secrets.AZURE_SERVICEACCOUNT}} Jira_User=${{secrets.JIRA_USER}} Jira_Pwd=${{secrets.JIRA_PWD}} Virustotal_Key=${{secrets.VIRUSTOTAL_KEY}}
        shell: bash