# This is a basic workflow to help you get started with Actions

name: CreatePlaybooksReadme

# Controls when the action will run.
# Allows you to run this workflow manually from the Actions tab and VS Code
on:
  # Allows you to run this workflow manually from the Actions tab and VS Code
  workflow_dispatch:

  # Allows you to run this workflow manually from VS Code
  repository_dispatch:
    types: [ createplaybooksreadme ]

  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths: 
    - 'Playbooks/**.json'

  pull_request:
    paths: 
    - 'Playbooks/**.json'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "validate-and-deploy"
  create-playbooks-readme:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Generate Playbooks Readme
        shell: bash
        run: |
          echo '![](https://www.metsys.fr/wp-content/themes/metsys/images/svg/metsys-logo.svg "Metsys")' > Playbooks/README.md
          echo '# Playbooks' >> Playbooks/README.md
          echo 'JSON files in this folder are ARM templates that define Playbooks that need to be deployed on a given Sentinel environment.' >> Playbooks/README.md
          find Playbooks/ -name '*.json' | while read file; do python Scripts/genmd_playbooks.py $file >> Playbooks/README.md; done

      - name: Commit Playbooks Readme
        run: |
          git config --global user.name ${{ secrets.GIT_USER }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git add Playbooks/README.md
          git commit -am "Automated Playbooks Readme"
          git push