# This is a basic workflow to help you get started with Actions

name: CreateWorkbooksReadme

# Controls when the action will run.
# Allows you to run this workflow manually from the Actions tab and VS Code
on:
  # Allows you to run this workflow manually from the Actions tab and VS Code
  workflow_dispatch:

  # Allows you to run this workflow manually from VS Code
  repository_dispatch:
    types: [ createworkbooksreadme ]

  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths: 
    - 'Workbooks/**.json'

  pull_request:
    paths: 
    - 'Workbooks/**.json'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "validate-and-deploy"
  create-workbooks-readme:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ secrets.ENV }}
                
      - name: Generate Workbooks Readme
        shell: bash
        run: |
          echo '[![Metsys](https://www.metsys.fr/wp-content/themes/metsys/images/svg/metsys-logo.svg)](https://www.metsys.fr/ "Metsys")' > Workbooks/README.md
          echo '# Workbooks' >> Workbooks/README.md
          echo 'JSON files in this folder are ARM templates that define Workbooks that need to be deployed on a given Sentinel environment.' >> Workbooks/README.md
          find Workbooks/ -name '*.json' | while read file; do python Scripts/genmd_workbooks.py $file >> Workbooks/README.md; done

      - name: Commit Workbooks Readme
        run: |
          git config --global user.name ${{ secrets.GIT_USER }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git add Workbooks/README.md
          git commit -am "Automated Workbooks Readme"
          git push