# This is a basic workflow to help you get started with Actions

name: CreateAnalyticsRulesReadme

# Controls when the action will run.
# Allows you to run this workflow manually from the Actions tab and VS Code
on:
  # Allows you to run this workflow manually from the Actions tab and VS Code
  workflow_dispatch:

  # Allows you to run this workflow manually from VS Code
  repository_dispatch:
    types: [ createanalyticsrulesreadme ]

  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths: 
    - 'AnalyticsRules/**.json'

  pull_request:
    paths: 
    - 'AnalyticsRules/**.json'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "validate-and-deploy"
  create-analyticsrules-readme:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        #with:
          #ref: ${{ secrets.ENV }}
      
      - name: Generate Analytics Rules Readme
        shell: bash
        run: |
          python Scripts/genmd_analyticsrules.py AnalyticsRules/analytics-rules.json > AnalyticsRules/README.md
          find AnalyticsRules/ -name '*.json' | grep -v "analytics-rules.json" | while read file; do python Scripts/genmd_analyticsrules.py $file > $file.md; done

      - name: Commit Analytics Rules Readme
        run: |
          git config --global user.name ${{ secrets.GIT_USER }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git add AnalyticsRules/*.md
          git commit -am "Automated Analytics Rules Readme"
          git push