# This is a basic workflow to help you get started with Actions

name: PSGenAnalyticsRules

# Controls when the action will run.
# Allows you to run this workflow manually from the Actions tab and VS Code
on:
  # Allows you to run this workflow manually from the Actions tab and VS Code
  workflow_dispatch:

  # Allows you to run this workflow manually from VS Code
  repository_dispatch:
    types: [ psgenanalyticsrules ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Generate Onboarding File
        shell: pwsh
        run: |
              Scripts/GenAnalyticsRules.ps1 -AnalyticsRulesFolder .\AnalyticsRules\ -TenantID ${{ secrets.TENANTID }} -SubscriptionID ${{ secrets.SUBSCRIPTIONID }} -Workspace ${{ secrets.WORKSPACE }} -GIT_USER ${{ secrets.GIT_USER }} -GIT_EMAIL ${{ secrets.GIT_EMAIL }} -Azure_User ${{ secrets.AZURE_USER }} -Azure_Pwd '${{ secrets.AZURE_PWD }}' -Outvariable issues
              $errors   = $issues.Where({$_.Severity -eq 'Error'})
              $warnings = $issues.Where({$_.Severity -eq 'Warning'})
              if ($errors) {
                  Write-Error "There were $($errors.Count) errors and $($warnings.Count) warnings total." -ErrorAction Stop
              } else {
                  Write-Output "There were $($errors.Count) errors and $($warnings.Count) warnings total."
              }

      - name: Commit AnalyticsRules Template
        run: |
          git config --global user.name ${{ secrets.GIT_USER }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git add AnalyticsRules/*
          git commit -am "Automated AnalyticsRules Template"
          git push